### ISSUE TITLE
Readme Correction

### ISSUE THREAD

**Issue by leviethung2103** [ducviet00/face-recognition-realtime#6]
Hi Duc Viet, 

Thank you for such a great work. 

I would like to ask you the content in the Readme file. You said that you got 45 FPS including Face Detection and Face Recognition stages by applying the Retina Face and face.evoLVe. 

However, in the table, you mentioned another Face Detection "ULFD" + face.evoLVe ~ 45 FPS. 

Which one you finally use for your project? Thank you in advance.

**Comment by ducviet00** [comment]
thanks for open issue
I forgot edit ULFD in benchmark table. It should be "Retina Face" which use Mobilenet0.25 as backbone. 
Performance is not affected by changing  face detector model.
